### ISSUE TITLE
Tracking: Improvements to `DefaultBodyLimit`

### ISSUE THREAD

**Issue by davidpdrsn** [tokio-rs/axum#1409]
https://github.com/tokio-rs/axum/pull/1400 will remove `ContentLengthLimit` in favor of `DefaultBodyLimit` but there a few things missing on `DefaultBodyLimit` for it to have feature parity with `ContentLengthLimit`:

- [ ] ~~We should make sure `GET`, `HEAD`, and `OPTIONS` requests without a body are still accepted. This can be done by checking the `content-length` and if that is not there apply `http_body::Limited`. Then since `GET`, `HEAD`, and `OPTIONS` doesn't have bodies we should never hit the limit. Will be nice if that works because it removes special casing of those methods.~~ Edit: I think we should drop this. Not really clear where to enforce this. In `Router`, `MethodRouter`, handlers, or extractors? Just checking in `Router` isn't enough since `MethodRouter` can be used without `Router`, and we don't wanna duplicate the check everywhere. If its really important correctness-wise then hyper should check it.
- [x] Currently `DefaultBodyLimit` has private APIs for actually enforcing the limit. This is used by `Bytes::from_request`. We should add a public API for that that `Multipart`, and other library developers, can use to get the same limiting the request of axum-core has. Could probably be a new method on `RequestExt` but since that isn't in `axum-core` it might require some exposing it there as well. Or maybe we move `RequestExt` to axum-core and re-export it from axum.
- [x] Clearly document the difference between [`RequestBodyLimit`](https://docs.rs/tower-http/latest/tower_http/limit/struct.RequestBodyLimit.html) and `DefaultBodyLimit`. The difference is that `DefaultBodyLimit` doesn't change the request body type in `Router<ReqBody>` (see https://github.com/tokio-rs/axum/issues/1110). Instead if applies the checks directly in the extractors themselves. Thus its more opt-in but easier to integrate, so its a trade-off which middleware one should use.

**Comment by jplatte** [comment]
I will take care of the second todo in the list.

**Comment by ttys3** [comment]
GET could have body

**Comment by davidpdrsn** [comment]
> may cause some existing implementations to reject the request

That means we're allowed to reject the request, which I think we should.

**Comment by jplatte** [comment]
> We should make sure `GET`, `HEAD`, and `OPTIONS` requests without a body are still accepted. This can be done by checking the `content-length` and if that is not there apply `http_body::Limited`. Then since `GET`, `HEAD`, and `OPTIONS` doesn't have bodies we should never hit the limit. Will be nice if that works because it removes special casing of those methods.

Where is this special-casing happening?

**Comment by davidpdrsn** [comment]
@jplatte ContentLengthLimit had checks for that here https://github.com/tokio-rs/axum/blob/0.5.x/axum/src/extract/content_length_limit.rs#L54

**Comment by jplatte** [comment]
I'm afraid I still don't really understand what has to change, but maybe that's fine and you'll just do the PR to tick the first checkbox 😄

**Comment by davidpdrsn** [comment]
I think we should just drop the first item. I elaborated a bit in the top comment.

So when https://github.com/tokio-rs/axum/pull/1461 is merged I think we'll be in a good place. I'll just close this for now.
